- id: '1630162475082'
  alias: Media Player leise bei Anruf
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sm_n975f_phone_state
    to: ringing
  condition: []
  action:
  - service: media_player.volume_set
    target:
      entity_id:
      - media_player.sonos_wohnzimmer_couch
      - media_player.sonos_arc_wohnzimmer
      - media_player.sonos_one_schlafzimmer
      - media_player.sonos_play_1_werkstatt
    data:
      volume_level: 0.1
  mode: single
- id: '1630163829406'
  alias: SMARTPHONE - Notification Akku leer
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.sm_n975f_battery_level
    to: '20'
    from: '21'
  condition: []
  action:
  - service: notify.mobile_app_sm_n975f
    data:
      message: Bitte lade das Smartphone auf. Es verbleiben nur noch 20% Akku.
  mode: single
- id: '1630216074327'
  alias: deCONZ - IKEA Tradfri Schlafzimmer
  description: ''
  use_blueprint:
    path: Bram_Kragten/deconz-ikea-five-button-remote-for-lights.yaml
    input:
      remote: b2ad82a7b7c848669b7286a48c0ff4c8
      button_left_short:
      - service: script.schlafzimmer_nacht
      button_left_long:
      - service: script.schlafzimmer_sexy_light
      button_right_short:
      - service: script.schlafzimmer_medium
      button_right_long:
      - service: script.schlafzimmer_hell
      light:
        entity_id: light.licht_schlafzimmer
- id: '1630219218437'
  alias: deCONZ - Philips Dimmschalter
  description: ''
  use_blueprint:
    path: sbyx/deconz-hue-dimmer-switch.yaml
    input:
      remote: 7f611988d45f6e230321ffd8d770dfbc
      on_press:
      - service: script.wohnzimmer_hell
        data: {}
      on_hold:
      - service: script.wohnzimmer_medium
        data: {}
      off_press:
      - service: script.wohnzimmer_aus
        data: {}
      off_hold:
      - service: script.wohnzimmer_nacht
        data: {}
      up_press:
      - service: script.wohnzimmer_konzentration
        data: {}
      up_hold: []
      down_press:
      - service: script.wohnzimmer_sexy_light
        data: {}
      down_hold: []
- id: '1630221547334'
  alias: Bewegungsmelder Werkstatt an
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_18
    to: 'on'
  condition:
  - condition: time
    after: 07:00
    before: '22:00'
  action:
  - service: script.werkstatt_hell
  mode: single
- id: '1630222239628'
  alias: Bewegungsmelder Werkstatt Licht aus
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_18
    to: 'off'
    for: '1:00:00'
  condition: []
  action:
  - service: script.werkstatt_aus
  mode: single
- id: '1631043708265'
  alias: LICHT - Wandschalter Wohnzimmer aus
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49c0f
    to: 'off'
  condition: []
  action:
  - service: script.wohnzimmer_aus
  mode: single
- id: '1631044733272'
  alias: LICHT - Wandschalter Wohnzimmer Tag - Wochenende/Urlaub
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49c0f
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.tagmodus_wochenende
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.nachtmodus_wochenende
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.turn_on
    target:
      entity_id:
      - script.wohnzimmer_hell
    data: {}
  mode: single
- id: '1631366464842'
  alias: LICHT - Wandschalter Wohnzimmer Nacht - Werktags
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49c0f
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.nachtmodus_werktags
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.tagmodus_werktags
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    target:
      entity_id: script.wohnzimmer_nacht
  mode: single
- id: '1631366601194'
  alias: LICHT - Wandschalter Wohnzimmer Tag - Werktags
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49c0f
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.tagmodus_werktags
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.nachtmodus_werktags
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    target:
      entity_id:
      - script.wohnzimmer_hell
    data: {}
  mode: single
- id: '1631366755112'
  alias: LICHT - Wandschalter Wohnzimmer Nacht - Wochenende/Urlaub
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49c0f
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.nachtmodus_wochenende
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.tagmodus_wochenende
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.turn_on
    target:
      entity_id: script.wohnzimmer_nacht
  mode: single
- id: '1631378221690'
  alias: LICHT - Wandschalter Schlafzimmer an
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.00085a49a49f84
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.licht_schlafzimmer_hell
  mode: single
- id: '1631378662274'
  alias: LICHT - Wandschalter Werkstatt aus
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49be1
    to: 'off'
  condition: []
  action:
  - service: script.werkstatt_aus
  mode: single
- id: '1631378722968'
  alias: LICHT - Wandschalter Werkstatt Nacht - Werktags
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49be1
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.nachtmodus_werktags
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.tagmodus_werktags
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.werkstatt_hell
  mode: single
- id: '1631379090949'
  alias: LICHT - Wandschalter Werkstatt Nacht - Wochenende/Urlaub
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49be1
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.nachtmodus_wochenende
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.tagmodus_wochenende
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.werkstatt_nacht
  mode: single
- id: '1631379147115'
  alias: LICHT - Wandschalter Werkstatt Tag - Werktags
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49be1
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.tagmodus_werktags
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.nachtmodus_werktags
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.werkstatt_hell
  mode: single
- id: '1631379212499'
  alias: LICHT - Wandschalter Werkstatt Tag - Wochenende/Urlaub
  description: ''
  trigger:
  - platform: state
    entity_id: switch.00085a49a49be1
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.tagmodus_wochenende
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.nachtmodus_wochenende
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.werkstatt_hell
  mode: single
- id: '1631379866625'
  alias: LICHT - Wandschalter Badezimmer aus
  description: ''
  trigger:
  - platform: state
    entity_id: switch.hmip_bsm_00085a49a4a57e
    to: 'off'
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.badezimmer_aus
  mode: single
- id: '1631379923167'
  alias: LICHT - Wandschalter Badezimmer Nacht - Werktags
  description: ''
  trigger:
  - platform: state
    entity_id: switch.hmip_bsm_00085a49a4a57e
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.nachtmodus_werktags
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.tagmodus_werktags
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    target:
      entity_id: script.badezimmer_nacht
  mode: single
- id: '1631379985933'
  alias: LICHT - Wandschalter Badezimmer Nacht - Wochenende/Urlaub
  description: ''
  trigger:
  - platform: state
    entity_id: switch.hmip_bsm_00085a49a4a57e
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.nachtmodus_wochenende
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.tagmodus_wochenende
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.turn_on
    target:
      entity_id: script.badezimmer_nacht
  mode: single
- id: '1631380075556'
  alias: LICHT - Wandschalter Badezimmer Tag - Werktags
  description: ''
  trigger:
  - platform: state
    entity_id: switch.hmip_bsm_00085a49a4a57e
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.tagmodus_werktags
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.nachtmodus_werktags
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.badezimmer_hell
  mode: single
- id: '1631380268367'
  alias: LICHT - Wandschalter Badezimmer Tag - Wochenende/Urlaub
  description: ''
  trigger:
  - platform: state
    entity_id: switch.hmip_bsm_00085a49a4a57e
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.tagmodus_wochenende
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
    before: input_datetime.nachtmodus_wochenende
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.badezimmer_hell
  mode: single
- id: '1631391812468'
  alias: MOTION SENSOR - Flur - LICHT - Flur an - Wochenende tagsüber
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_9
    - binary_sensor.presence_12
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.tagmodus_wochenende
    before: input_datetime.nachtmodus_wochenende
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.flur_hell
  mode: single
- id: '1631392127589'
  alias: MOTION SENSOR - Flur - LICHT - Flur Timer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_9
    - binary_sensor.presence_12
    to: 'on'
  condition: []
  action:
  - service: timer.start
    data: {}
    target:
      entity_id: timer.bewegungsmelder_flur
  mode: single
- id: '1631398918230'
  alias: MOTION SENSOR - Flur - LICHT - Flur aus
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bewegungsmelder_flur
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.flur_aus
    data: {}
  mode: single
- id: '1631398974078'
  alias: MOTION SENSOR - Flur - LICHT - Flur an - Werktags Nacht
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_12
    - binary_sensor.presence_9
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.nachtmodus_werktags
    before: input_datetime.tagmodus_werktags
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    target:
      entity_id: script.flur_nacht
    data: {}
  mode: single
- id: '1631399071620'
  alias: MOTION SENSOR - Flur - LICHT - Flur an - Werktags tagsüber
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_12
    - binary_sensor.presence_9
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.tagmodus_werktags
    before: input_datetime.nachtmodus_werktags
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.flur_hell
  mode: single
- id: '1631399107802'
  alias: MOTION SENSOR - Flur - LICHT - Flur an - Wochenende Nacht
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_12
    - binary_sensor.presence_9
    to: 'on'
  condition:
  - condition: time
    after: input_datetime.nachtmodus_wochenende
    before: input_datetime.tagmodus_wochenende
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - service: script.turn_on
    target:
      entity_id: script.flur_nacht
    data: {}
  mode: single
- id: '1672004851347'
  alias: MOTION SENSOR - Küche - LICHT - Licht an
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 8dbcd74b4bbd4af68d2e60c0237c5312
    entity_id: binary_sensor.presence_21
    domain: binary_sensor
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.hmip_bsm_00085a49a49be7
  mode: single
- id: '1672780505823'
  alias: LICHT - Wandschalter Schlafzimmer aus
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.00085a49a49f84
    to: 'off'
  condition: []
  action:
  - service: scene.turn_on
    data: {}
    target:
      entity_id: scene.licht_schlafzimmer_aus
  mode: single
- id: '1693847374649'
  alias: Frigate Notifications (0.12.0.1)
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.eingang
      notify_device: fac89688300f48feab9317e8f694c80f
      labels: []
      presence_filter: person.philipp
      state_filter: false
      attachment: snapshot
      message: '{{ label }} detected - {{ camera_name }}'
      silence_timer: 240
- id: '1706648446084'
  alias: Voice Assist  - Wohnzimmer hell
  description: Voice Assist  - Wohnzimmer hell
  trigger:
  - platform: conversation
    command: Wohnzimmer hell
  condition: []
  action:
  - service: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.wohnzimmer_hell
  mode: single
- id: '1706648549884'
  alias: Voice Assist  - Wohnzimmer medium
  description: Voice Assist  - Wohnzimmer medium
  trigger:
  - platform: conversation
    command:
    - Wohnzimmer medium
  condition: []
  action:
  - service: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.wohnzimmer_medium
  mode: single
- id: '1706648769592'
  alias: Voice Assist  - Wohnzimmer Nacht
  description: Voice Assist  - Wohnzimmer Nacht
  trigger:
  - platform: conversation
    command:
    - Wohnzimmer Nacht
    - Wohnzimmer nacht
    - Wohnzimmer dunkel
  condition: []
  action:
  - service: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.wohnzimmer_nacht
  mode: single
- id: '1706649110047'
  alias: Voice Assist  - Wohnzimmer Sexy Light
  description: Voice Assist  - Wohnzimmer Sexy Light
  trigger:
  - platform: conversation
    command:
    - Wohnzimmer Sexy Light
  condition: []
  action:
  - service: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.wohnzimmer_sexy_light
  - service: tts.cloud_say
    data:
      cache: false
      entity_id: media_player.sonos_arc_wohnzimmer
      message: Viel Spaß!
  mode: single
- id: '1706653049390'
  alias: Voice Assist - Wohnzimmer aus
  description: Voice Assist - Wohnzimmer aus
  trigger:
  - platform: conversation
    command: Wohnzimmer aus
  condition: []
  action:
  - service: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.wohnzimmer_aus
  mode: single
- id: '1706764930693'
  alias: Voice Assist - Wohnzimmer Boost
  description: Voice Assist - Wohnzimmer Boost
  trigger:
  - platform: conversation
    command: Wohnzimmer Boost
  condition: []
  action:
  - service: script.wohnzimmer_boost
    metadata: {}
    data: {}
    response_variable: Wohnzimmer Boost eingeschaltet
  mode: single
- id: '1706935406070'
  alias: Voice Assist - Wohnzimmer Tageslicht
  description: Voice Assist - Wohnzimmer Tageslicht
  trigger:
  - platform: conversation
    command:
    - Wohnzimmer Tageslicht
  condition: []
  action:
  - service: script.wohnzimmer_tageslicht
    data: {}
    response_variable: 'message: "erledigt"'
  mode: single
- id: '1706936332341'
  alias: Voice Assist  - Wohnzimmer Konzentration
  description: Voice Assist  - Wohnzimmer Konzentration
  trigger:
  - platform: conversation
    command:
    - Wohnzimmer Konzentration
  condition: []
  action:
  - service: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.wohnzimmer_konzentration
  mode: single
