#
# Configure a default setup of Home Assistant (frontend, api, etc)
#
default_config:
#
# ALLOW CUSTOMISATION OVER CUSTOMIZE.YAML FILE
#
homeassistant:
  customize: !include customize.yaml
#
# AUTH PROVIDERS
#
  auth_providers:
    - type: homeassistant
#
# MEDIA SOURCE
#
media_source:
#
# FRONTEND
#
frontend:
  themes: !include_dir_merge_named themes
#
# LOGGER
#
logger:
  default: info
  logs:
    homeassistant.components.shell_command: debug
    homeassistant.components.webhook: debug
    custom_components.extended_openai_conversation: info
#
# INCLUDES
#
group: !include groups.yaml
automation: !include automations.yaml
automation frigate: !include_dir_list ./automations/frigate
script: !include scripts.yaml
scene: !include scenes.yaml
#
# INPUT SELECT
#
input_select:
  minimalist_ui_switch:
    name: Select popup/view
    options:
      - wohnzimmer_deckenleuchte
      - wohnzimmer_kleine_lampe
      - wohnzimmer_stehlampe
      - wohnzimmer_lightstrip
      - schlafzimmer_deckenleuchte
      - schlafzimmer_hue_go
      - schlafzimmer_stehlampe
      - nachttisch_links
      - nachttisch_rechts
      - badezimmer_deckenleuchte
      - spiegel_links
      - spiegel_rechts
      - werkstatt_deckenleuchte
      - flur_deckenleuchte
      # - light 2
      - samsung_q7_series
      - sonos_arc
      - sonos_couch
      - chromecast_schlafzimmer
      - sonos_schlafzimmer
      - google_nest_mini_bad
      - google_nest_mini_kueche
      - sonos_werkstatt
      - climate 1
      - climate 2
      - climate 3
      - climate 4
      - climate 5
      # - power 1
      # - power 2
      - wohnzimmer
      - schlafzimmer
      - badezimmer
      - kueche
      - werkstatt
      - flur
      - dachterrasse
      - remote
      - kalender
#
# CONVERSATION
#
conversation:
#
# SENSOREN
#
sensor:
#
# TAGESZEIT
#
  - platform: time_date
    display_options:
      - "time"
#
# Open Hardware Monitor
#
  - platform: openhardwaremonitor
    host: 192.168.178.65
    port: 8085
#
# HOMEMATIC INTEGRATION
#
homematic:
  interfaces:
    HomeMatic Funk:
      host: 192.168.178.37
      #port: 2001
      resolvenames: "json"
      username: !secret homematic_username
      password: !secret homematic_password
    HomeMatic IP:
      host: 192.168.178.37
      port: 2010
      resolvenames: "json"
      username: !secret homematic_username
      password: !secret homematic_password
#    HomeMatic Wired:
#      host: 192.168.178.37
#      port: 2000
#      resolvenames: json
#      username: !secret homematic_username
#      password: !secret homematic_password
    groups:
      host: 192.168.178.37
      port: 9292
      resolvenames: "json"
      username: !secret homematic_username
      password: !secret homematic_password
      path: /groups
  hosts:
    ccu3:
      host: 192.168.178.37
      port: 2001
      username: !secret homematic_username
      password: !secret homematic_password
#
#
###LIGHT GROUPS###
#
#
#
# WOHNZIMMER DECKENLEUCHTE LIGHT-GROUP
#
light:
  - platform: group
    name: Lichtgruppe Wohnzimmer Deckenleuchte
    entities:
      - light.wohnzimmer_deckenlampe_01
      - light.wohnzimmer_deckenlampe_02
      - light.wohnzimmer_deckenlampe_03
#
# WOHNZIMMER GESAMT LIGHT-GROUP
#
  - platform: group
    name: Lichtgruppe Wohnzimmer gesamt
    entities:
      - light.wohnzimmer_deckenlampe_01
      - light.wohnzimmer_deckenlampe_02
      - light.wohnzimmer_deckenlampe_03
      - light.wohnzimmer_kleine_lampe
      - light.wohnzimmer_lampe_rechts
      - light.wohnzimmer_lightstrip

#
# FLUR LIGHT-GROUPS
#
  - platform: group
    name: Lichtgruppe Flur Deckenleuchte
    entities:
      - light.flur_deckenleuchte_01
      - light.flur_deckenleuchte_02
      - light.flur_deckenleuchte_03
#
# WERKSTATT LIGHT-GROUPS
#
  - platform: group
    name: Lichtgruppe Werkstatt Deckenleuchte
    entities:
      - light.werkstatt_deckenleuchte_01
      - light.werkstatt_deckenleuchte_02
      - light.werkstatt_deckenleuchte_03
      - light.werkstatt_deckenleuchte_04
      - light.werkstatt_deckenleuchte_05
      - light.werkstatt_deckenleuchte_06
#
# BADEZIMMER LIGHT-GROUPS
#
  - platform: group
    name: Lichtgruppe Badezimmer Spiegelbeleuchtung
    entities:
      - light.badezimmer_spiegel_01
      - light.badezimmer_spiegel_02
#
# BADEZIMMER GESAMT LIGHT-GROUP
#
  - platform: group
    name: Lichtgruppe Badezimmer gesamt
    entities:
      - light.badezimmer_spiegel_01
      - light.badezimmer_spiegel_02
      - light.badezimmer_deckenleuchte
#
# CIRCADIAN LIGHTING
#
#
# CIRCADIAN LIGHTING WOHNZIMMER
#
circadian_lighting:
switch:
  - platform: circadian_lighting
    name: "Wohnzimmer"
    lights_ct:
      - light.wohnzimmer_deckenlampe_01
      - light.wohnzimmer_deckenlampe_02
      - light.wohnzimmer_deckenlampe_03
      - light.wohnzimmer_kleine_lampe
      - light.wohnzimmer_lampe_rechts
      - light.wohnzimmer_lightstrip
#
# CIRCADIAN LIGHTING SCHLAFZIMMER
#
  - platform: circadian_lighting
    name: "Schlafzimmer"
    lights_ct:
      - light.schlafzimmer_deckenleuchte
      - light.schlafzimmer_philips_hue_go
      - light.schlafzimmer_standleuchte
      - light.schlafzimmer_nachttisch_philipp
#
# CIRCADIAN LIGHTING WERKSTATT
#
  - platform: circadian_lighting
    name: "Werkstatt"
    lights_ct:
      - light.werkstatt_deckenleuchte_01
      - light.werkstatt_deckenleuchte_02
      - light.werkstatt_deckenleuchte_03
      - light.werkstatt_deckenleuchte_04
      - light.werkstatt_deckenleuchte_05
      - light.werkstatt_deckenleuchte_06
#
# CIRCADIAN LIGHTING BADEZIMMER
#
  - platform: circadian_lighting
    name: "Badezimmer"
    lights_ct:
      - light.badezimmer_spiegel_01
      - light.badezimmer_spiegel_02
      - light.badezimmer_deckenleuchte
#
# CIRCADIAN LIGHTING FLUR
#
  - platform: circadian_lighting
    name: "Flur"
    lights_ct:
      - light.flur_deckenleuchte_01
      - light.flur_deckenleuchte_02
      - light.flur_deckenleuchte_03
#
# API INTEGRATION
#
api:
#
# TELEGRAM BOT INTEGRATION
#
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids: 
      - !secret telegram_chat
#
# TELEGRAM NOTIFY
#
notify:
  - platform: telegram
    name: Telegram Smart Home Alerts Bot
    chat_id: !secret telegram_chat
#
# RASPBERRY CPU TEMPERATURE
#
command_line:
  - sensor:
      name: CPU Temperature
      command: "cat /sys/class/thermal/thermal_zone0/temp"
      # If errors occur, make sure configuration file is encoded as UTF-8
      unit_of_measurement: "°C"
      value_template: "{{ value | multiply(0.001) | round(1) }}"


