id: '163084011705642'
alias: Batteriewarnung - Lichtsensor Pflanzschrank
description: ''
trigger:
- platform: state
  to: '33'
  entity_id: sensor.lichtsensor_pflanzschrank_batterie_prozent
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Lichtsensor im Pflanzschrank. Es werden
      zwei AA-Batterien benötigt.
mode: single