id: '1630761595153'
alias: Batteriewarnung - Bewegungsmelder Wohnzimmer Kamin
description: ''
trigger:
- platform: state
  to: '10'
  entity_id: sensor.bewegungsmelder_battery_level
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien bei Bewegungsmelder Wohnzimmer Kamin. Es
      werden zwei AAA-Batterien benötigt.
mode: single