id: '1630164052293'
alias: Batteriewarnung - Bewegungsmelder Wohnzimmer TV
description: ''
trigger:
- platform: state
  entity_id: sensor.presence_3_battery_level
  to: '10'
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien bei Bewegungsmelder Wohnzimmer TV. Es werden
      zwei AAA-Batterien benötigt.
mode: single