id: '1630839882225'
alias: Batteriewarnung - Heizthermostat Wohnzimmer
description: ''
trigger:
- platform: state
  entity_id: sensor.heizthermostat_wohnzimmer_batterie_prozent
  to: '33'
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Heizthermostat im Wohnzimmer. Es werden
      zwei AA-Batterien benötigt.
mode: single