id: '1630840319299'
alias: Batteriewarnung - Türsensor Wohnzimmer
description: ''
trigger:
- platform: state
  to: '33'
  entity_id: sensor.tuersensor_wohnzimmer_batterie_prozent
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Türsensor im Wohnzimmer. Es werden
      zwei AAA-Batterien benötigt.
mode: single