id: '1630840031642'
alias: Batteriewarnung - Heizthermostat Wohnzimmer TV
description: ''
trigger:
- platform: state
  entity_id: sensor.heizthermostat_wohnzimmer_tv_batterie_prozent
  to: '33'
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Heizthermostat Wohnzimmer TV. Es werden
      zwei AA-Batterien benötigt.
mode: single