id: '1630839656878'
alias: Batteriewarnung - Philips Dimmschalter
description: ''
trigger:
- platform: state
  entity_id: sensor.philips_dimmschalter_battery_level
  to: '10'
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien bei dem Philips Dimmschalter. Es wird eine
      CR2450 Knopfzelle benötigt.
mode: single