id: '1630761427237'
alias: Batteriewarnung - Bewegungsmelder Badezimmer
description: ''
trigger:
- platform: state
  to: '10'
  entity_id: sensor.bewegungsmelder_battery_level_3
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien bei Bewegungsmelder Badezimmer. Es werden
      zwei AAA-Batterien benötigt.
mode: single