id: '1630840285085'
alias: Batteriewarnung - Türsensor Werkstatt
description: ''
trigger:
- platform: state
  to: '33'
  entity_id: sensor.tuersensor_werkstatt_batterie_prozent
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Türsensor in der Werkstatt. Es werden
      zwei AAA-Batterien benötigt.
mode: single