id: '1630839992474'
alias: Batteriewarnung - Heizthermostat Werkstatt
description: ''
trigger:
- platform: state
  entity_id: sensor.heizthermostat_werkstatt_batterie_prozent
  to: '33'
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Heizthermostat in der Werkstatt. Es
      werden zwei AA-Batterien benötigt.
mode: single