id: '1630840670000'
alias: Batteriewarnung - Thermostat Werkstatt
description: ''
trigger:
- platform: state
  to: '33'
  entity_id: sensor.thermostat_werkstatt_batterie_prozent
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Thermostat in der Werkstatt. Es werden
      zwei AAA-Batterien benötigt.
mode: single