id: '1630762110795'
alias: Batteriewarnung - Bewegungsmelder Werkstatt
description: ''
trigger:
- platform: state
  to: '10'
  entity_id: sensor.bewegungsmelder_werkstatt_battery_level
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien bei Bewegungsmelder Werkstatt. Es werden
      zwei AAA-Batterien benötigt.
mode: single