id: '1630761745304'
alias: Batteriewarnung - Bewegungsmelder Flur
description: ''
trigger:
- platform: state
  to: '10'
  entity_id: sensor.bewegungsmelder_battery_level_2
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien bei Bewegungsmelder Flur. Es werden zwei
      AAA-Batterien benötigt.
mode: single