id: '1631019447833'
alias: Batteriewarnung - Lichtsensor Dachterrasse
description: ''
trigger:
- platform: state
  to: '33'
  entity_id: sensor.lichtsensor_terrasse_batterie_prozent
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Lichtsensor auf der Dachterrasse.
      Es werden zwei AA-Batterien benötigt.
mode: single