id: '1630840826655'
alias: Batteriewarnung - Thermostat Schlafzimmer
description: ''
trigger:
- platform: state
  to: '33'
  entity_id: sensor.thermostat_schlafzimmer_batterie_prozent
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Thermostat im Schlafzimmer. Es werden
      zwei AAA-Batterien benötigt.
mode: single