id: '1630839788709'
alias: Batteriewarnung - Heizthermostat Schlafzimmer
description: ''
trigger:
- platform: state
  entity_id: sensor.heizthermostat_schlafzimmer_batterie_prozent
  to: '33'
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Heizthermostat im Schlafzimmer. Es
      werden zwei AA-Batterien benötigt.
mode: single