id: '1630761138807'
alias: Batteriewarnung - IKEA Tradfri Fernbedienung
description: ''
trigger:
- platform: state
  entity_id: sensor.tradfri_fernbedienung_battery_level
  to: '10'
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien bei der IKEA Tradfri Fernbedienung. Es
      wird eine CR2032 Knopfzelle benötigt.
mode: single