id: '1630761488377'
alias: Batteriewarnung - Bewegungsmelder Schlafzimmer
description: ''
trigger:
- platform: state
  to: '10'
  entity_id: sensor.bewegungsmelder_battery_level_5
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien bei Bewegungsmelder Schlafzimmer. Es werden
      zwei AAA-Batterien benötigt.
mode: single