id: '1629312683309758942'
alias: Lichtwecker
description: ''
trigger:
- platform: state
  entity_id: sensor.minutes_next_alarm_philipp
  id: trigger_id
  to: '3'
condition: []
action:
- service: light.turn_on
  data:
    transition: 180
    kelvin: 3200
    brightness: 255
  target:
    entity_id:
    - light.dimmable_light_22
    - light.extended_color_light_2
    - light.licht_schlafzimmer_standleuchte
    - light.extended_color_light_3_2
    - light.licht_nachttischleuchte_philipp
- delay:
    hours: 0
    minutes: 2
    seconds: 0
    milliseconds: 0
- service: switch.turn_on
  target:
    entity_id: switch.00085a49a49f84
mode: single