id: '1630839955310'
alias: Batteriewarnung - Heizthermostat Küche
description: ''
trigger:
- platform: state
  entity_id: sensor.heizthermostat_kueche_batterie_prozent
  to: '33'
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Heizthermostat in der Küche. Es werden
      zwei AA-Batterien benötigt.
mode: single