id: '1630840787087'
alias: Batteriewarnung - Thermostat Küche
description: ''
trigger:
- platform: state
  to: '33'
  entity_id: sensor.thermostat_kueche_batterie_prozent
condition: []
action:
- service: notify.mobile_app_sm_n975f
  data:
    message: Bitte tausche die Batterien beim Thermostat in der Küche. Es werden
      zwei AAA-Batterien benötigt.
mode: single