id: '1629116432477'
alias: Bewegungsmelder Küche Licht an
description: ''
trigger:
- type: motion
  platform: device
  device_id: 8dbcd74b4bbd4af68d2e60c0237c5312
  entity_id: binary_sensor.presence_21
  domain: binary_sensor
  for:
    hours: 0
    minutes: 0
    seconds: 0
    milliseconds: 0
condition: []
action:
- service: switch.turn_on
  target:
    entity_id: switch.hmip_bsm_00085a49a49be7
mode: single